### ISSUE TITLE
Latest release doesn't change the fish color when status != 0

### ISSUE THREAD

**Issue by amir20** [fisherman/dartfish#3]
<img width="956" alt="screen shot 2016-04-22 at 11 32 32 am" src="https://cloud.githubusercontent.com/assets/260667/14751279/f584156c-087d-11e6-8c23-4f8a6fcf27a2.png">

Trying to figure out why this is happening.

**Comment by lordlycastle** [comment]
I believe it's because you don't have your `fish_color_error` variable set.

**Comment by amir20** [comment]
```
⨉⪧ ~ ⟩ echo $fish_color_error                                                                                                         11:37
f30
⨉⪧ ~ ⟩                                                                                                                                11:37
```

**Comment by amir20** [comment]
It is set. Do I need to set it somewhere else?

**Comment by amir20** [comment]
Ps. this is a new install of fisher and dartfish.

**Comment by sotayamashita** [comment]
@lordlycastle 

> I believe it's because you don't have your fish_color_error variable set.

Well We should set $fish_color_error ? or Is it defined in other files ?

**Comment by sotayamashita** [comment]
@amir20 What's happen if you set color `$fish_color_error` ?

**Comment by amir20** [comment]
I don't understand what you mean. It is already set to something. 

```
set | grep error                                                                                                              
fish_color_error f30
```

**Comment by amir20** [comment]
If I do a fresh install, it should just work, right?

**Comment by lordlycastle** [comment]
@amir20 I think it wasn't set before the install, if any of the colour variables used by the prompt are not set when it's run, they're set to `normal` so it doesn't give any errors. Can you try setting `fish_color_error` to purple to see if it changes?

@sotayamashita You can set it to whatever you like with `set -x fish_color_error purple`, if it's not set it'll default to `normal`. You can edit all these colour scheme with the `fish_config` command.

**Comment by amir20** [comment]
I did `set -x fish_color_error purple` and started a new tab. Nothing happens. I don't think this is a problem with the color not being set. I have done a fresh install and started a new session multiple times.

**Comment by lordlycastle** [comment]
Hmm... One other thing that can be causing this is `set_custom_colors` function which I believe is run when installed, this is not longer necessary as we're using user's colours. I forgot to remove this file.

**Comment by sotayamashita** [comment]
@lordlycastle `fish_color_error` is default variable in fish and we can change it with `fish_config` right ?

**Comment by lordlycastle** [comment]
> @lordlycastle fish_color_error is default variable in fish and we can change it with fish_config right ?
Yep, just by customising the theme.

**Comment by amir20** [comment]
I tried playing around with fish_prompt. 

```
if test "$status_copy" -ne 0
        echo "ERROR" # this never gets printed
        set status_color $fish_color_error
    end
```
I don't know what else to try. It used to work.

**Comment by lordlycastle** [comment]
Ok, so it has to do with updating to `fisher` 2.0 because I just updated it, and mine's broken too!
@bucaran Thoughts?

**Comment by amir20** [comment]
I fixed it. `set -l status_copy $status` should be first thing that is copied. The `for` loop overwrites the value of `$status`.

**Comment by amir20** [comment]
I can send a pull request if you want?

**Comment by lordlycastle** [comment]
Yes, please. 
IDK why it's like that through.

**Comment by lordlycastle** [comment]
@amir20 Umm... I am still getting the same colour. Better luck with you?

**Comment by amir20** [comment]
It works for me right now. I did `fisher u` and confirmed that the latest is there.

**Comment by bucaran** [comment]
Is this fixed? :)

**Comment by sotayamashita** [comment]
@amir20 ping

**Comment by amir20** [comment]
As I already said, it works for me. 👍🏻

**Comment by bucaran** [comment]
Oops, I didn't notice the issue was already closed, thanks.
